pod:
  numberOfNginxReplicas: 3

loadBalancer:
  lbShape: flexible
  lbMinShape: 10
  lbMaxShape: 100
  lbListenerPort: 80

image:
  repository: <OCIR_REPO>
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.1.0-${BUILDRUN_HASH}
